-- CREATE TABLE
DROP TABLE PRODUCT;

CREATE TABLE PRODUCT
(
    prod_no    VARCHAR2(20)
        CONSTRAINT PK_PRODUCT PRIMARY KEY,
    prod_name  VARCHAR2(30)
        CONSTRAINT UQ_NN_NAME UNIQUE NOT NULL,
    prod_price NUMBER(20)
        CONSTRAINT CK_PRICE CHECK (prod_price > 0)
);

ALTER TABLE PRODUCT
ADD prod_quantity NUMBER(20);

