DROP SEQUENCE CUSTOMER_NO_SEQ;

CREATE SEQUENCE CUSTOMER_NO_SEQ_DEFAULT;

CREATE SEQUENCE CUSTOMER_NO_SEQ
INCREMENT BY 3
MAXVALUE 10
MINVALUE 2
NOCYCLE; -- MAX 넘어가면 오류발생

SELECT CUSTOMER_NO_SEQ_DEFAULT.nextval
FROM dual;
SELECT CUSTOMER_NO_SEQ_DEFAULT.currval
FROM dual;

-- 실무 AUTO_INCREMENT 적용법
CREATE SEQUENCE customer_no_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE customers
(
    customer_id NUMBER DEFAULT customer_no_seq.NEXTVAL PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL
);